/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jdjz_myapplication_MainActivity */

#ifndef _Included_com_jdjz_myapplication_MainActivity
#define _Included_com_jdjz_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jdjz_myapplication_MainActivity
 * Method:    getStringNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jdjz_myapplication_MainActivity_getStringNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
